DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS sessions;

CREATE TABLE users (
  user_id VARCHAR(250) PRIMARY KEY,
  full_name VARCHAR(250) DEFAULT NULL,
  email VARCHAR(250) DEFAULT NULL,
  password VARCHAR(250) NOT NULL,
  created_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE sessions (
    user_id VARCHAR(250) PRIMARY KEY,
    access_key VARCHAR(250) NOT NULL,
    secret_key VARCHAR(250) NOT NULL,
    created_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)